name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: ['8.2', '8.3']
        laravel-version: ['9.x', '10.x', '11.x']

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: composer, php-cs-fixer, phpunit, phpstan

      - name: Remove composer.lock
        run: rm -f composer.lock

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ matrix.php-version }}-${{ matrix.laravel-version }}-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-${{ matrix.php-version }}-${{ matrix.laravel-version }}

      - name: Install dependencies
        run: |
          composer require laravel/framework:${{ matrix.laravel-version }} --no-update
          composer install --no-scripts --no-progress --prefer-dist

      - name: Run PHPUnit tests
        run: vendor/bin/phpunit --coverage-text --colors=never

      - name: Run PHPStan
        run: vendor/bin/phpstan analyse --memory-limit=2G
